server:
  port: 8181

spring:
  application:
    name: zuul-api-gateway
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_db?createIfNotExists=true
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  
      
zuul:
  ignored-services:
  - '*'
 
  - Cookie,Set-Cookie        
  routes:
#      fdfdf:
#         service-id: custom-service
#         path: /**
      user-service:
         service-id: user-service
         path: /user
         
         #zuul.routes.brain-service.path=/api/v1/**
#zuul.routes.brain-service.service-id=BRAIN-SERVICE

#zuul.routes.auth-service.strip-prefix=false
#zuul.routes.brain-service.strip-prefix=false

      
    